[fields]
names = ["timestamp", "source", "target"]

[input]
name = "List"

	[input.config]
	files=["testdata/input.csv.zst"]

[output]
name = "FileWriter"
procs=1

	[output.config]
	PathString="./_out/output.csv.gz"
