# This topology reads a zstandard file containing multiple loglines, filters them using
# the Clause filter and saves the matching lines into a gz file
[csv]
field_separator="2c"

[input]
name="List"

    [input.config]
    files=["./examples/data/list-clause-files-comma-sep.csv.zst"]

[[filter]]
name="ClauseFilter"

    [filter.config]
    Clause="""(or (fieldA value5) (fieldC value6))"""

[output]
name="Files"
procs=1

    [output.config]
    PathString="/tmp/baker/{{.Year}}{{.Month}}{{.Day}}-{{.Hour}}{{.Minute}}{{.Second}}.log.gz"
