# This topology reads a zstandard file containing multiple loglines, filters them using
# the Clause filter and saves the matching lines into a gz file
[csv]
field_separator="\u001e"

[input]
name="List"

    [input.config]
    files=["./examples/data/list-clause-files-record-sep.csv.zst"]

[[filter]]
name="ClauseFilter"

    [filter.config]
    Clause="""(or (timestamp value5) (target value6))"""

[output]
name="Files"
procs=1

    [output.config]
    PathString="./_out/output-list-clause-files-record-sep.csv.gz"
