name: Coverage
on: [pull_request]
jobs:
  build:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
            fetch-depth: 2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Coverage
        env:
          CODECOV_TOKEN: 863a635e-5c68-4b66-9f81-b41cb835de2e
        run: |
            make -- --ci-cover
            curl -s https://codecov.io/bash | bash
