name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: gofmt
        run: make gofmt

      - name: govet
        run: make govet

      - name: go mod verify
        run: go mod verify

      - name: goimports
        run: |
            go get golang.org/x/tools/cmd/goimports
            test -z "$(goimports -d . | tee /dev/stderr)"

      - name: Test
        run: make test

      - name: Compile tests/benchmarks
        run: make compile-tests

      - name: Build all examples
        run: go build ./examples/...
