name: Linux CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Lint / Static checks
        run: |
          make gofmt
          make govet
          go mod verify
          go install golang.org/x/tools/cmd/goimports
          test -z "$(goimports -d . | tee /dev/stderr)"

      - name: Test
        run: make test

      - name: Compile tests/benchmarks
        run: make compile-tests

      - name: Build all examples
        run: go build ./examples/...

      - name: Build with extras
        run: CGO_ENABLED=1 go build -tags cgo_sqlite ./examples/advanced/
