name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.15.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: build
        run: go build