name: Windows CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~\go\pkg\mod
            %LocalAppData%\go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: go build

      - name: Test
        run: go test -timeout 2m ./...

      - name: Compile tests/benchmarks
        run: make compile-tests

      - name: Build all examples
        run: go build ./examples/...
